# Welcome to your introduction in Python programming!


![coding.jpeg]()

Python is a computer programming language used extensively by astronomers. In this introduction, we will show you how to write Python code that will then get turned into instructions your computer can interpret and execute.

We will use Python a lot during the class, and it is nearly unavoidable if you work in the field of astronomy or physics.

**Observerational** astronomers/astrophysicists will often use Python to sort, arrange, and analyze astronomical images taken with telescopes. Beyond this, they may want to extract physical information from their data or do statistical analyses. Python excells at this!

**Theoretical** astronomers/astrophysicists will often want to understand how a model works under a variety of circumstances, or to explore the relationships between certain quantities. They can use Python to look at and manipulate equations, or they may develop full simulations which allow them to see the behavior of a theory play out in a "toy universe".

---

What you are seeing right now is called a **Python Notebook** and it is being run on the site Google Colab.

You can also run this notebook *locally* on your computer if you download the file (the suffix ".ipynb" tells your computer this is a **py**thon **n**ote**b**ook), but you'll need to make sure you have python installed on your device. The nice thing about Google Colab is that it runs completely in your browser, which means you won't need to download anything locally to your device.

We have chosen to use Goolge Colab for the duration of the class, and all coding assignments will be sent to you in this format. However, if you prefer, we welcome you to download the file and open it in any format you prefer. Just note that you will need to submit your homeworks as ".ipynb" files.

For now, let's assume we're all in Google Colab, and let's start exploring. 😀



---



# Part A.
### Print statements, strings, variables, basic arthimetic, comments, errors, & computer logic



---

The very first line of code most people learn in any language is the Hello World statement. The line of code in the cell below will tell the computer to print out to the screen the characters "Hello World".

To execute the cell, first click in the cell and then press **shift+enter** at the same time.

If you just press enter, it will create a new line (like in many word documents). You'll need to press **shift+enter** at the same time to "run the cell", or execute the code written in the cell.

In [ ]:
print('Hello World')

Hello World

Hooray! It worked!
You should now see a green check mark to the left of the cell, and the words "Hello World" should have printed beneath the cell.

The first major lesson here is: computers are very picky about how we tell them to do things.
For example, if we do not include parenthesis in our print statement, instead of printing out "Hello World" we get a *syntax error*.

Try running the cell below and see what happens.

In [ ]:
print 'Hello World'

Do you see a red circle with an exclamation mark appear to the left of the cell? And instead of printing "Hello World", we get a message that says: *SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?*

This is called an **error message**. You may one day start to hate seeing them (this is a joke among many experienced coders!), but they are actually extremely useful for debugging your code. For example, our error message tells us right away that the reason for our error is the missing parentheses, and it gives us an example of how we should write our code instead when it says "Did you mean...". Now we know that we can try again and write `print('Hello World')` instead of just `print 'Hello World'`.

What other things is the computer picky about?

If you do not include single or double quotes around the words you want printed, you will also get a syntax error.

Try running the cell below without quotation marks around the phrase Hello World and see what happens.

In [ ]:
print(Hello World)

This time your syntax error message is not quite so helpful. Are we really missing a comma? No- but the computer is taking a guess. This time it's wrong, so keep in mind that the computer can't do everything for us. We'll need to think critically ourselves, too.

So why didn't our print statement work when we left out the quotation marks? It's because the quotation marks tell our computer that the data type is a *string*. A string is a fancy name for a group of characters. It is different from a number (ie: 1, -10, 55.8) or from a variable (ie: x, Variable1) which represents a number.
Think of Python like a calculator-- if you type in 2+2, your calculator understands. If you type random words or characters in your calculator, it won't understand because those characters don't have preassigned definitions. A string is a way to tell python (or a calculator), these are some characters and I want them all kept together! "Hello World" is a bunch of characters and we want them kept topgether.

That's why the print function works when we use `print("Hello World")` but fails when we try `print(Hello World)`. In the latter example, your computer is wondering "what variable is Hello?? What variable is World?? And if we're printing two variables, shouldn't they be separated by a comma?"

We'll talk more about variables soon, but for now, let's see what else we can do with the print function. We can print out numbers.
Note that numbers should *not* be in quotes unless you want to make them part of some text.

In [ ]:
# print a number:
print(1)

# and print a string below it:
print('You can include anything in quotes like so: 1,?,%')

What's the green text in the above cell that starts with the "#" symbol? Those are called comments, and they are ignored by python when we run the cell. Their main purpose is for human readers to better understand what the code is doing. We will use comments on our code in class very often, and it is good practice to do so.

So now that we can make our computers print out messages, how do we make this useful? Python has basic math included directly in the language. You can do basic addition, subtraction, multiplication, division, and exponentiation with numbers directly like so.

In [ ]:
print(1 + 1)

Note that the spaces between the numbers and the plus sign are optional. They are there to make the code easier to read. For example, the code below works, but is hard to read. Try to stick to a consistent, easy to understand spacing in your code.

In [ ]:
print(1+                     1 )

Now what happens if we do not want to do all of our math at once or maybe reuse some result? We can use *variables* to hold values and get those values back in the future. The format for creating a variable is like so:

letters_underscores_or_numbers = some_value

Note that a variable name must always start with a letter. The following two cells create a variable **x** with the value **3** and then prints out the result of **x + 2**.

In [ ]:
# our variable name will be 'x' and we will set it equal to 3
x = 3

In [ ]:
# now when you execute this cell, the variable x will be treated as the number 3
print(x + 2)

Taking this one step further, we can create another variable and perform math without any numbers directly in the print statement.

In [ ]:
# make a new variable named 'y'
y = 5
# use the earlier definition of 'x' and our new defintion of 'y' to do some arithmetic:
print(x - y)

A quick note: if you are getting errors about things being "undefined", make sure you have run all the cells. If you don't run a cell, your computer doesn't know it exists.

We can also perform some math and store the result in a variable like so:

In [ ]:
# define a new variable 'z' which is the result of the operation (x * y -4)
z = x * y - 4

# print the new variable
print(z)

What happens if a variable **y** is created using the variable **x** and then we change the value of the variable **x**. Before running this code, try to guess what the output of the two print statements will produce.

In [ ]:
x = 2
y = x + 3
print(y)
x = 4
print(y)

As you can see, changing the value of **x** does not change the value of **y**. To explain, when **y** is created, it takes the result of whatever is on the right and then assigns this to the variable **y**. It does not re-evaluate the statement `x + 3` each time we try to retrieve the value stored in **y**. This is another example of how much ORDER MATTERS in computer logic.

Contrastingly, let's look at the same example again but deliberately re-evaluate the statement `x+3`.

In [ ]:
x = 2
y = x + 3
print(y)
x = 4
y = x + 3
print(y)

Do you see how the above example differs from the example before it?

You probably will not use this much in this class, but you can assign strings of characters to variables as well like so:

In [ ]:
hello = 'Hello World'
print(hello)

However, if you try to treat the variable **hello** like a number and perform math with it, you will get an error.

In [ ]:
print(hello - 2)

One neat part about the print function is that we can print out many objects at a time by putting a comma between the objects. For example, the cell below prints out the value of the variable **x** along with some text that explains what the number means.

In [ ]:
print('This is the value of x: ', x)

---
# Exercises for Part A.
---

Exercise 1

Write a line of code that prints out "My name is ..." where you replace the ... with your name.

In [ ]:
# Write your print statement here and execute the cell

Excercise 2

Write five lines of code that each print out the addition(+), subtraction(-), multiplication(\*), division(/), and exponentiation(**) of two numbers. Include at least one number with a decimal point and at least one negative number.

In [ ]:
# Write your five print statements here, one statement for each operation, and execute the cell

Exercise 3

Write two lines of code that prints out the result of `5 * (2 + 3) \*\* 2` and `5 \* 2 + 3 \*\* 2`. Does Python follow the standard order of operations?

In [ ]:
# Write your two print statements here and execute the cell.
# Notice whether you get the same answer for both statements.

Exercise 4

Write a line of code that prints out the addition(+) of two strings. Remember that each string will be enclosed in quotation marks, ie: "happy" and "birthday". Do you think the other operators(-,\*,...) also work on strings? Try it out.

In [ ]:
# Write your print statement here, and see what happens if you use different operations instead of the plus sign



---

# Part B.
### Functions: Defining, calling, arguments, scope, & return


---

We have already encountered the print function. It takes one or more *arguments* and prints them to the screen.

An argument, in short, is what goes inside the parentheses. It is special value, variable, string, or object that you are asking the function to use. In the print function, we have used the argument `"Hello World"`.  

Functions themselves take zero or more arguments and then return zero or more values. For example, we can **define a function** that takes no arguments (empty parentheses) and just executes one pre-set print statement.

In [ ]:
def myFirstFunction():
  print('You called my function')

Notice the format when we define a function. We always begin with the word "def". This tells Python that what comes next is a *def*inition. We then write the name of our function (in this case, it's called myFirstFunction) and follow it with parentheses`()` and a colon `:`.

Then we hit the `enter` key to start the next line. But notice the way the next line is indented. This indent is required when defining a function.

We can *call* our function just like we call the print function. ("Calling" a function is equivalent to using a function)

In [ ]:
# this is how you call the function
myFirstFunction()

If we try giving it an argument, we will get an error. This is because we defined the function to not expect any arguments.

In [ ]:
# this cell will give an error
myFirstFunction(2)

Now, how will functions interact with variables? Try to guess what the code block below will print out, then run the cell and check if you were correct.

In [ ]:
# Here we define the function
def mySecondFunction():
  x = 3
  print(x)

# Here we call the fucntion
mySecondFunction()

Let's look at some computer logic. What do you think the following code will do?

In [ ]:
x = 1
mySecondFunction()
print(x)

Functions have their own *scope*. Scope basically means they only care about code inside them and most code outside of them has no effect. So in the case above, their is one variable *x* defined outside the function and another variable *x* defined inside the function that is completely separate from the other *x*.

`mySecondFunction` contains a variable x assigned to be equal to 3, and it contians a print statement of its variable x. That's why it prints 3.

However, outside of the function, we have defined the *global* variable x to be equal to 1. When we call `print(x)`, we print the global variable x, so it prints 1.

Functions can also return values using a return statement.

In [ ]:
# Here we define the function
def thisFunctionReturnsFive():
  return 5

Calling the function on its own won't have any effect. (Alright I lied a bit. Python notebooks like Google Colab print whatever the last line of code outputs, so it would actually print 5. However, if you run python not in a notebook, the 5 would be lost and not printed. We can supress the printing of the last line in notebooks by using a semicolon)

In [ ]:
# Here we call the function
# We use a semicolon here only for demonstration purposes
thisFunctionReturnsFive();

If we want to print the value returned by the function, we can use the print statement and pass the value returned by our function to the print function.

In [ ]:
# Here we call the print function on our new function
print(thisFunctionReturnsFive())

 Now lets set up some functions that depend on arguments. We do this by adding variable names separated by commas inside the parentheses. The example below is a function called `add` which depends on two arguments, `x` and `y`.

In [ ]:
# Define a function which depends on the variables x and y
def add(x, y):
  return x + y

And now we have a function that adds two values and returns the result. As of right now, the arguments x and y are essentially placeholders. When you call the function, you must specify what you want x and y to represent.

In [ ]:
# Call the function by speicying that x is 1, and that y is 8
print(add(1, 8))

In the example below, try setting new values to the variables a, b, and x. Then run the cell a few times and make sure things work how you imagine they should!

In [ ]:
a = 3
b = 6
x = 2
print(add(a, b))
print(add(a, x))
print(add(x**2, (a-b)))
print(add((a-x),(b-x)**3))

---
# Exercises for Part B.
---

Exercise 1

Write a function that takes in two numbers and returns the product of the two numbers. Check that it works.

In [ ]:
# Write your code here

Exercise 2

Write a function that takes three numbers and returns the value of the following formula $a * b^x + b * a^x$

In [ ]:
# Write your code here

**BONUS**
If you already have some experience with python and are familiar with if/else statements, have a look at this next exercise.

If you are brand new to python, feel free to have a look too, but do not worry if this feels too advanced for the moment. We will discuss everything in depth once in class.

Write five functions. One function must be called `simple_calculator` and it must take a string and two numbers as its arguments. The string is one of "add", "sub", "mul", "div". Write four other functions that add, subtract, multiply, and divide two numbers. Then, depending on the string, have *simple_calculator* call the appropriate function and return the result. Check that it works.

In [ ]:
# Write your code here

---



# Part C.
### Plotting: line plots, scatter plots, NumPy arrays, nested arrays, dimensionality, indexing



---
To make plots in Python, we want to import a library called Matplotlib.

In [ ]:
# the following line imports the plotting library we want and names it "plt"
import matplotlib.pyplot as plt

# this next line is a python magic function which makes our plots print inside the notebook
%matplotlib inline

Let's try out a simple plot.

In [ ]:
#Let's define some x and y-coordinates:
x= [1,2,3] # x is now a "list" object with three elements inside
y= [1,2,3] # y is now a "list" object with three elements inside

#plotting to our canvas
plt.plot(x,y)

#showing what we plotted
plt.show()

Now let's add a title and labels.

In [ ]:
#Try some different x and y-coordinates:
x= [3,5,7,8]
y= [2,1,5,4]

plt.plot(x,y)

plt.title('Title')
plt.xlabel('x-axis')
plt.ylabel('y-axis')

plt.show()

We can also plot more than one line at the same time.

In [ ]:
#one set of domain values
x= [3,5,7,8]

#first set of range values
y1= [2,1,5,4]
#second set of range values
y2= [5,2,4,3]

plt.plot(x,y1,color='r')
plt.plot(x,y2,color='b')

#try commenting out the plotting commands above and un-commenting the following:
#plt.plot(x,y1,color='r',label='y1 data')
#plt.plot(x,y2,color='b',label='y2 data')
#plt.legend()

plt.title('Title')
plt.xlabel('x-axis')
plt.ylabel('y-axis')

plt.show()

There are several different kinds of plots you can make: line graphs like the ones above will be important for this class, but we will also look at scatter plots.

In [ ]:
#our first scatter plot

star_xcoord = [83, 90, 71, 80, 100, 87, 92, 99, 40, 34]
star_ycoord = [70, 39, 15, 20, 17, 99, 12, 66, 87, 58]

# now we use the command plt.scatter instead of plt.plot
plt.scatter(star_xcoord,star_ycoord,color='magenta')
plt.xlabel('star x coordinate')
plt.ylabel('star y coordinate')
plt.title('Star Positions')

plt.grid() #makes a grid in the background
plt.show()

For this class, there are two other libraries that we will want to import: NumPy and Pandas. Each are very powerful tools for data analysis and we'll explore them much more in the coming days. For now, we'll focus just on NumPy.

In [ ]:
import numpy as np

A NumPy array is 50 times faster than a list in Python, and this can matter if you're working with a big data file (and astronomers/astrophysicists often are).

In [ ]:
#To make a NumPy array, you call numpy by using the function "np.array()"
arr = np.array([1,2,3,4,5]) #this turns a list of elements into a NumPy array

print(arr)
print(type(arr))

You can also have nested arrays, or arrays with 2 (or more) dimensions

In [ ]:
oneD_array = np.array([1,2,3,4,5])

twoD_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# the innermost square brackets show you two separate lists
# the outer square brackets show how there's a big list that contains the two lists which are separated by a comma
# the outermost parentheses show that the big list is contained in a NumPy array

print(oneD_array)
print(twoD_array)

You can check the number of dimensions and the shape of a numpy array like so:

In [ ]:
xD_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [5, 4, 3]]])

#print the dimensions
print(xD_array.ndim)

#print the shape
print(xD_array.shape)

Our shape is 2, 2, 3. What does that mean?

It means that once we open up our array, we see **2** lists (two sets of outer square brackets).
Let's look at just one of those lists; let's zoom in on this part:
`[[1, 2, 3], [4, 5, 6]]`.
We can see that inside this part, there are **2** lists, each in a set of square brackets.

If we focus on just one of the lists, let's zoom in on this part:
`[1, 2, 3]`. We can see that there are **3** elements in this list.

That's what the shape is trying to tell us. **2, 2, 3**. 2 outer lists, each with 2 inner lists, each with 3 elements.

**Indexing and slicing**

Let's say we want the first element in a one-dimensional array.

In [ ]:
arr = np.array([1,2,3,4,5])

#Python indexing starts at 0.
print(arr[0])

What about the last element?

In [ ]:
#If we start at 0, what is the index of our last element?

print(arr[4])

You can also do the above example another way using negative indexing:

In [ ]:
#negative indexing starts at the last element in your array and works backwards towards the first element

print(arr[-1])

print(arr[-2])

In [ ]:
#We can also do funky stuff like grab the 2nd and 4th elements of the array and add them

print(arr[1] + arr[3])

Indexing with a 2D array:

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

#What happens if we try to print the first element of this 2D array?

print(arr[0])

The first element of that 2D array is a list, and so we print the whole list. What if we want the first element of that first list?

In [ ]:
print(arr[0][0])

What about the 3rd element of the 2nd list?

In [ ]:
print(arr[1][2])

---
# Exercises for Part C.
---

Excercise 1

Create a 2d numpy array with shape (2,10). You can fill it with an numbers you like. Print the shape to show that it is indeed (2, 10).

In [ ]:
# Your code goes here

Excercise 2

Make a scatter plot of the first dimension of your 2D array versus the second dimension of your 2D array.

In [ ]:
# Your code goes here

Exercise 3

The following array has 5 elements with the value 3. Print each of these elements by calling the appropriate index.

In [ ]:
new_array = np.array([[[1, 2, 3], [4, 5, 6], [3, 9, 1]], [[1, 2, 3], [4, 3, 6], [3, 5, 6]]])

# write your five print statements here. The output should print the number 3 five times.



---

# Nice work! ✨

We hope this has been a good opportunity to play around with python. It takes time to improve, so try not to beat yourself up if you found this challenging. The point is to get exposure and start the learning process.

In class, we will walk through this entire notebook together and make sure you each understand the whole thing. Soon you will be able to effectively use Python as a tool for astrophysical research.